savchenkolex/mimino-group-21

- src/partials/header.html
- src/partials/hero.html
> Mainpage hero

- src/css/hotel.css
- src/css/styles.css
- src/hotel-page.html
- src/partials/hotel-room-1.html
- src/partials/hotel-room-2.html
- src/partials/hotel-room-3.html
- src/partials/hotel-room-hero.html
Добавив контейнер  , змінив свої стилі добавив контейнер в hotel page змінив hotel-hero
> changed html hotel page,hotel.css , container

- src/partials/restaurant-details.html
Створено секцію, додано абзаци і параграфи та дві кнопки. До кнопки "Забронювати столик" підключено модальне вікно. Інша кнопка "Переглянути меню" при натискані переходить на сторінку меню ресторану. Зараз граюсь зі свайпом. не можу зрозуміти як його підключити, на відео Іван підключав лінк з сайту https://swiperjs.com/ в index.html. Куди мені вставляти цей лінк?
> make rastaurant-details

- src/index.html
- src/partials/restaurant-kitchen.html
- src/restaurant-page.html
fix name section
пофіксив секції
> fix name section

- src/css/hotel-room-amenities.css
- src/partials/hotel-room-amenities.html
> Change media

- src/css/contacts.css
- src/css/hotel-about.css
- src/css/hotel-details.css
- src/css/styles.css
- src/partials/contacts.html
- src/partials/hotel-details.html
lexNight.log
-------------------------------
<main> открывается в hero.html, hotel-hero.html, hotel-room-hero.html, restaurant-hero.html и закрывается в footer.html перед футером. @Вікторія Рожкова @Дима @Крістіна Литвиненко 
@Дима твой код с hotel-room-hero.html был перенесён в hotel-hero.html - этот файл и должен быть файлом секции херо страницы hotel-page.html файл hotel-room-hero - относится к странице room-page.htlm  @Anna Burkova 
Подключил модалку room-price-modal-window на странице hotel-page.html @Дима @Катерина 
<div class="container> должен отрывается внутри каждой секции и закрывается перез закрытием каждой секции. Кое-где так уже сделал.
Додав всі потрібні і не портібні шрифти до файлу стилів через @font-face  і трохи поексперементував, як це працює на hotel-page 
Почав …
> contacts,colors,logo

- src/partials/restaurant-kitchen.html
добавил новые изображение нужного формата и разрешение
> make new 1x 2x tablet and desktop

- src/css/restaurant-kitchen.css
- src/partials/restaurant-kitchen.html
добавил стили для десктопа
исправил цвета через VAR
> make desftop styles

- src/css/hotel.css
- src/partials/hotel-room-1.html
- src/partials/hotel-room-2.html
- src/partials/hotel-room-3.html
> origin-hotel

- src/css/hotel.css
- src/partials/hotel-room-1.html
- src/partials/hotel-room-2.html
- src/partials/hotel-room-3.html
> added slider for hotel

- src/css/restaurant-kitchen.css
- src/partials/restaurant-kitchen.html
изменил шрифт для заголовка,исправил баги с последними картинками
> change font from mimino

- src/css/about-restaurant.css
- src/css/restaurant-kitchen.css
- src/partials/restaurant-kitchen.html
постралась виправити картинку в секції під hero на головній сторінці та ресторану
> about-restaurant

- src/css/hotel.css
Змінив позиціювання нижніх картинок
> fixed position hotel-section

- src/css/header.css
- src/css/hotel-room-hero.css
- src/partials/hotel-room-hero.html
добавила тінь та відстум в мобільній версії для header
> Gradient hotel room

- src/css/about-restaurant.css
- src/css/restaurant-kitchen.css
- src/partials/about-restaurant.html
- src/partials/restaurant-kitchen.html
исправил шрифты,добавил скрытый заголовок.изменил на верное позиционирование картинок,
> make changes

- src/css/footer.css
- src/css/hotel-details.css
- src/partials/footer.html
вирівняв елементи
виставив різницю гапів по медіа
пофіксив зламаний утілітарний класс .container
додав ховер на елементи
оформлення кнопочок.
> footer final

- src/css/hotel.css
> overfow hidden hotel sect

- src/css/hero.css
Виправила падінги у кнопок (була проблема  в тому, що при планшетній версії кнопки були з перенесенням рядку
> hero-button-padding

- src/partials/contacts.html
боротьба за відображення фото мапи на сторінці))
> fix paths in srcset. again

- src/css/about-restaurant.css
- src/css/restaurant-kitchen.css
- src/partials/restaurant-kitchen.html
робила те, що й перед цим, але на сторінці ресторану
> restro-img
